### ISSUE TITLE
Questions about blockchain interoperability based on pub-sub architecture

### ISSUE THREAD

**Issue by EurusLiao** [hyperledger-labs/pubsub-interop#15]
Hi~Thank you very much for your previous answers, I am very interested in this paper.
After reading the paper and the source code, I have some questions about the blockchain interoperability based on pub-sub architecture.
1. How do subscribers subscribe to topics they are interested in? My understanding from the source code is that subscribers directly subscribe based on topicID,but it seems that there is no process of asking the broker. Is there any assumptions? For example, the subscriber knows in advance which topics the publisher will publish.
2. How does the subscriber understand the topic content published by the publisher, that is, how to achieve semantic interoperability?  If the description of the topic is inconsistent between the publisher and the subscriber, how can the broker match?
Looking forward to your answer, thank you very much!

**Comment by ghaemisr** [comment]
Hello @EurusLiao, thank you for your interest in this project and for your great questions. 

1. Your understanding is correct. The subscribers use the topicIDs to subscribe to a topic. In order to understand what topics are available, the subscribers can use the queryAllTopics functionality to retrieve all the available topics on the broker blockchain. Having said that, I totally understand your point. A function that supports retrieving topics based on publishers can be valuable. If you are interested in working on this, you can create a new issue for it and assign it to yourself.

2. Your second question brings up a great point. In the current implementation, we assume that the publisher will publish the topics in a way that everyone can understand. Since the subscriber cannot change the topic, there won't be any inconsistency in the communication.  For future versions, we can think about ways that this process can be improved.

**Comment by EurusLiao** [comment]
> Hello @EurusLiao, thank you for your interest in this project and for your great questions.
> 
> 1. Your understanding is correct. The subscribers use the topicIDs to subscribe to a topic. In order to understand what topics are available, the subscribers can use the queryAllTopics functionality to retrieve all the available topics on the broker blockchain. Having said that, I totally understand your point. A function that supports retrieving topics based on publishers can be valuable. If you are interested in working on this, you can create a new issue for it and assign it to yourself.
> 2. Your second question brings up a great point. In the current implementation, we assume that the publisher will publish the topics in a way that everyone can understand. Since the subscriber cannot change the topic, there won't be any inconsistency in the communication.  For future versions, we can think about ways that this process can be improved.

Thank you for your answer. It's very helpful to me. And happy weekend~
